create table if not exists ecm_tenants (
    tenant varchar(255) primary key,
    schema_name varchar(255),
    root_id int8,
    "data" jsonb
);

create table if not exists ecm_mimetypes (
    id int8 not null generated by default as identity,
    file_extension varchar(255) not null,
    mimetype varchar(255) not null,
    priority int4 not null,
    constraint ecm_mimetypes_pkey primary key (id)
);

create index if not exists ix_ecm_mimetypes_ext on ecm_mimetypes using btree (file_extension);
create unique index if not exists ix_ecm_mimetypes_mt_uq on ecm_mimetypes using btree (mimetype, file_extension);
