/* Index ECM Engine - A system for managing the capture (when created
 * or received), classification (cataloguing), storage, retrieval,
 * revision, sharing, reuse and disposition of documents.
 *
 * Copyright (C) 2008 Regione Piemonte
 * Copyright (C) 2008 Provincia di Torino
 * Copyright (C) 2008 Comune di Torino
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 */
package it.doqui.index.ecmengine.mtom.exception;

import jakarta.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.2.3 Thu Sep 10 12:32:50 CEST 2009
 * Generated source version: 2.2.3
 * 
 */

@WebFault(name = "SystemException", targetNamespace = "http://server.mtom.ecmengine.index.doqui.it/")
public class SystemException_Exception extends Exception {
    public static final long serialVersionUID = 20090910123250L;

    private SystemException systemException;

    public SystemException_Exception() {
	super();
    }

    public SystemException_Exception(String message) {
	super(message);
    }

    public SystemException_Exception(String message, Throwable cause) {
	super(message, cause);
    }

    public SystemException_Exception(String message, SystemException systemException) {
	super(message);
	this.systemException = systemException;
    }

    public SystemException_Exception(String message, SystemException systemException, Throwable cause) {
	super(message, cause);
	this.systemException = systemException;
    }

    public SystemException getFaultInfo() {
	return this.systemException;
    }
}
