package it.doqui.libra.librabl.domain.policy;

public enum OperationOption {
    ALLOW_MANAGED_PROPERTIES,
    IGNORE_MANAGED_PROPERTIES,
    HANDLE_CONTENT_PROPERTIES,
    DISCARD_UNKOWN_PRESENT_METADATA,
    IGNORE_INVALID_CONTENT,
    FAIL_IF_PATH_EXISTS,
    CREATE_MISSING_PARENTS
}
